<?php

namespace testMovemberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * testMovemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testMovemberRepository extends EntityRepository
{
}
